info = {
    "total": 28,
    "total_pages": 28,
    "results": [
        {
            "id": "eMGFk-dkGYA",
            "slug": "a-person-in-a-small-boat-on-a-large-body-of-water-eMGFk-dkGYA",
            "alternative_slugs": {
                "en": "a-person-in-a-small-boat-on-a-large-body-of-water-eMGFk-dkGYA",
                "es": "una-persona-en-un-bote-pequeno-en-un-gran-cuerpo-de-agua-eMGFk-dkGYA",
                "ja": "大きな水域に浮かぶ小さなボートに乗った人-eMGFk-dkGYA",
                "fr": "une-personne-dans-un-petit-bateau-sur-un-grand-plan-deau-eMGFk-dkGYA",
                "it": "una-persona-in-una-piccola-barca-su-un-grande-specchio-dacqua-eMGFk-dkGYA",
                "ko": "큰-물-위에-작은-보트를-타고-있는-사람-eMGFk-dkGYA",
                "de": "eine-person-in-einem-kleinen-boot-auf-einem-grossen-gewasser-eMGFk-dkGYA",
                "pt": "uma-pessoa-em-um-pequeno-barco-em-um-grande-corpo-de-agua-eMGFk-dkGYA",
                "id": "seseorang-di-perahu-kecil-di-perairan-besar-eMGFk-dkGYA",
            },
            "created_at": "2024-09-09T10:36:02Z",
            "updated_at": "2026-03-17T03:04:13Z",
            "promoted_at": None,
            "width": 2519,
            "height": 3751,
            "color": "#c0c0c0",
            "blur_hash": "LGFireWAV[V[Dif5IBWC~qxuM{WB",
            "description": "雷峰塔 leifeng pagoda",
            "alt_description": "A person in a small boat on a large body of water",
            "breadcrumbs": [],
            "urls": {
                "raw": "https://images.unsplash.com/photo-1725878045572-b531e634bad3?ixid=M3w4OTc3NzZ8MHwxfHNlYXJjaHwxfHwlRTYlOUQlQUQlRTUlQjclOUUlRTglQTUlQkYlRTYlQjklOTZ8ZW58MHx8fHwxNzczNzI2MDQxfDA&ixlib=rb-4.1.0",
                "full": "https://images.unsplash.com/photo-1725878045572-b531e634bad3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4OTc3NzZ8MHwxfHNlYXJjaHwxfHwlRTYlOUQlQUQlRTUlQjclOUUlRTglQTUlQkYlRTYlQjklOTZ8ZW58MHx8fHwxNzczNzI2MDQxfDA&ixlib=rb-4.1.0&q=85",
                "regular": "https://images.unsplash.com/photo-1725878045572-b531e634bad3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4OTc3NzZ8MHwxfHNlYXJjaHwxfHwlRTYlOUQlQUQlRTUlQjclOUUlRTglQTUlQkYlRTYlQjklOTZ8ZW58MHx8fHwxNzczNzI2MDQxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                "small": "https://images.unsplash.com/photo-1725878045572-b531e634bad3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4OTc3NzZ8MHwxfHNlYXJjaHwxfHwlRTYlOUQlQUQlRTUlQjclOUUlRTglQTUlQkYlRTYlQjklOTZ8ZW58MHx8fHwxNzczNzI2MDQxfDA&ixlib=rb-4.1.0&q=80&w=400",
                "thumb": "https://images.unsplash.com/photo-1725878045572-b531e634bad3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4OTc3NzZ8MHwxfHNlYXJjaHwxfHwlRTYlOUQlQUQlRTUlQjclOUUlRTglQTUlQkYlRTYlQjklOTZ8ZW58MHx8fHwxNzczNzI2MDQxfDA&ixlib=rb-4.1.0&q=80&w=200",
                "small_s3": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1725878045572-b531e634bad3",
            },
            "links": {
                "self": "https://api.unsplash.com/photos/a-person-in-a-small-boat-on-a-large-body-of-water-eMGFk-dkGYA",
                "html": "https://unsplash.com/photos/a-person-in-a-small-boat-on-a-large-body-of-water-eMGFk-dkGYA",
                "download": "https://unsplash.com/photos/eMGFk-dkGYA/download?ixid=M3w4OTc3NzZ8MHwxfHNlYXJjaHwxfHwlRTYlOUQlQUQlRTUlQjclOUUlRTglQTUlQkYlRTYlQjklOTZ8ZW58MHx8fHwxNzczNzI2MDQxfDA",
                "download_location": "https://api.unsplash.com/photos/eMGFk-dkGYA/download?ixid=M3w4OTc3NzZ8MHwxfHNlYXJjaHwxfHwlRTYlOUQlQUQlRTUlQjclOUUlRTglQTUlQkYlRTYlQjklOTZ8ZW58MHx8fHwxNzczNzI2MDQxfDA",
            },
            "likes": 4,
            "liked_by_user": False,
            "bookmarked": False,
            "current_user_collections": [],
            "sponsorship": None,
            "topic_submissions": {
                "travel": {"status": "rejected"},
                "architecture-interior": {"status": "rejected"},
                "street-photography": {"status": "rejected"},
                "nature": {"status": "rejected"},
                "wallpapers": {"status": "rejected"},
                "textures-patterns": {"status": "rejected"},
                "spirituality": {"status": "rejected"},
            },
            "asset_type": "photo",
            "user": {
                "id": "zK4a1qy55_I",
                "updated_at": "2026-03-06T03:54:25Z",
                "username": "d_ks11",
                "name": "Dominic Kurniawan Suryaputra",
                "first_name": "Dominic Kurniawan",
                "last_name": "Suryaputra",
                "twitter_username": None,
                "portfolio_url": None,
                "bio": "📷",
                "location": "Sydney",
                "links": {
                    "self": "https://api.unsplash.com/users/d_ks11",
                    "html": "https://unsplash.com/@d_ks11",
                    "photos": "https://api.unsplash.com/users/d_ks11/photos",
                    "likes": "https://api.unsplash.com/users/d_ks11/likes",
                    "portfolio": "https://api.unsplash.com/users/d_ks11/portfolio",
                },
                "profile_image": {
                    "small": "https://images.unsplash.com/profile-1717901151541-881c3d6ead4fimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
                    "medium": "https://images.unsplash.com/profile-1717901151541-881c3d6ead4fimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
                    "large": "https://images.unsplash.com/profile-1717901151541-881c3d6ead4fimage?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
                },
                "instagram_username": "dominicsuryaputra",
                "total_collections": 2,
                "total_likes": 1206,
                "total_photos": 1193,
                "total_free_photos": 1193,
                "total_promoted_photos": 12,
                "total_illustrations": 0,
                "total_free_illustrations": 0,
                "total_promoted_illustrations": 0,
                "accepted_tos": True,
                "for_hire": True,
                "social": {
                    "instagram_username": "dominicsuryaputra",
                    "portfolio_url": None,
                    "twitter_username": None,
                    "paypal_email": None,
                },
            },
        }
    ],
}
